### ISSUE TITLE
Problem with exceeding coordinate space

### ISSUE THREAD

**Issue by iona5** [iona5/coordinator#6]
Happens when changing CRS
```
2020-03-04T13:10:19     WARNING    Traceback (most recent call last):
              File ".../AppData/Roaming/QGIS/QGIS3\profiles\coordinator-dev/python/plugins\coordinator\coordinator.py", line 410, in inputCoordinatesChanged
              #Coordinator.log("Input changed")
              File ".../AppData/Roaming/QGIS/QGIS3\profiles\coordinator-dev/python/plugins\coordinator\coordinator.py", line 380, in process
              # coordinatorLog("Input: %f %f " % (x, y) )
             _core.QgsCsException: forward transform of
             (inf, inf)
             PROJ: +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=utm +zone=33 +ellps=WGS84
             Error: latitude or longitude exceeded limits
```

**Comment by iona5** [comment]
still open, relates also to reprojection of coordinates when switching CRS
